from pwn import *
#p = process("./bread")
p = remote('mc.ax', 31796)
x = p.recv()
p.sendline("add flour")
x = p.recv()
p.sendline("add yeast")
x = p.recv()
p.sendline("add salt")
x = p.recv()
p.sendline("add water")
x = p.recv()
p.sendline("hide the bowl inside a box")
x = p.recv()
p.sendline("wait 3 hours")
x = p.recv()
p.sendline("work in the basement")
x = p.recv()
p.sendline("preheat the toaster oven")
x = p.recv()
p.sendline("set a timer on your phone")
x = p.recv()
p.sendline("watch the bread bake")
x = p.recv()
p.sendline("pull the tray out with a towel")
x = p.recv()
p.sendline("open the window")
x = p.recv()
p.sendline("unplug the oven")
x = p.recv()
p.sendline("unplug the fire alarm")
x = p.recv()
p.sendline("flush the bread down the toilet")
x = p.recv()
p.sendline("wash the sink")
x = p.recv()
p.sendline("clean the counters")
x = p.recv()
p.sendline("get ready to sleep")
x = p.recv()
p.sendline("close the window")
x = p.recv()
p.sendline("replace the fire alarm")
x = p.recv()
p.sendline("brush teeth and go to bed")
p.interactive()